### ISSUE TITLE
...Server didn't respond 

### ISSUE THREAD

**Issue by Scrumps1** [ConnorSwis/GPT.lua#1]
The program starts but every time I try to chat with the Ai I get the response of  "..Server didn't respond"

**Comment by ConnorSwis** [comment]
Please check your `computercraft-server.toml` file to ensure the `action` setting under `http.rules` is set to `allow`:
```toml
[http]
	enabled = true
	websocket_enabled = true
	max_requests = 16
	max_websockets = 4

	[http.bandwidth]
		global_download = 33554432
		global_upload = 33554432

	[[http.rules]]
		host = "$private"
		action = "allow"

	[[http.rules]]
		max_websocket_message = 131072
		host = "*"
		max_upload = 4194304
		action = "allow"
		max_download = 16777216
		timeout = 30000
```
